### ISSUE TITLE
panic: [1812 0x714] The specified image file did not contain a resource section.

### ISSUE THREAD

**Issue by edufsrj** [go-graphics/go-gui-projects#10]
I'm using windows 11 and I tried to run the example in the documentation and it panics with this error:

```panic: [1812 0x714] The specified image file did not contain a resource section.

goroutine 1 [running, locked to thread]:
github.com/rodrigocfd/windigo/win.HINSTANCE.LoadImage(0xd60000, {0x1, 0x3e8, {0x0, 0x0}}, 0x1, 0x10, 0x10, 0x0)
        C:/Users/Eduardo/go/pkg/mod/github.com/rodrigocfd/windigo@v0.0.0-20230123221028-c635f6096afe/win/hinstance_user.go:137 +0x114
github.com/rodrigocfd/windigo/ui.(*_WindowBase).loadIcons(0xc000000000?, 0xd6c3a8?, 0x3e8)
        C:/Users/Eduardo/go/pkg/mod/github.com/rodrigocfd/windigo@v0.0.0-20230123221028-c635f6096afe/ui/WindowBase.go:107 +0x45
github.com/rodrigocfd/windigo/ui.(*_WindowRaw).generateWcx(0xc000053300?, 0xc000117ef8, 0x0?, {0x0, 0x0}, 0x117ea8?, 0xc000117ec8?, 0xdf2e86?, 0xe08d20?)
        C:/Users/Eduardo/go/pkg/mod/github.com/rodrigocfd/windigo@v0.0.0-20230123221028-c635f6096afe/ui/WindowRaw.go:40 +0x79
github.com/rodrigocfd/windigo/ui.(*_WindowRawMain).RunAsMain(0xc000026080)
        C:/Users/Eduardo/go/pkg/mod/github.com/rodrigocfd/windigo@v0.0.0-20230123221028-c635f6096afe/ui/WindowRawMain.go:55 +0x10c
main.main()
        C:/Users/Eduardo/desenvolvimento/go/winClippy/main.go:60 +0x2b
exit status 2```

**Comment by go101** [comment]
@edufsrj, Do you mean you encountered a problem in using https://github.com/rodrigocfd/windigo? You can directly create an issue in that project.

**Comment by zigo101** [comment]
@edufsrj 
As this project doesn't handle issues of each included UI project. I will close this issue now.
